Missing abstract method in ConfigForm
    Fatal error: Class Drupal\hugs\Form\ConfigForm contains 1 abstract method and must therefore be
    declared abstract or implement the remaining methods 
    (Drupal\Core\Form\ConfigFormBase::getEditableConfigNames) in 
    C:\git\web\code\src\modules\custom\hugs\src\Form\ConfigForm.php on line 8

Added (on best guess):

  public function getEditableConfigNames() {
    return ['hugs.settings'];
  }